on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
jobs:
    request:
        name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
            args: ${{ on.rss.outputs.contentSnippet }}
